:concurrency: 1
:queues:
  - ['default', 1]
  - ['document_classification', 1]
  - ['document_classification_monitor_job', 1]
  - ['ocr', 1]
  - ['ocr_monitor_job', 1]
  - ['form_deep_understanding', 1]
:timeout: 7200

:schedule:
  # OcrJob:
  #   every: '10s'
  #   queue: ocr
  #   enabled: true
  # DocumentClassificationJob:
  #   every: '10s'
  #   queue: document_classification
  #   enabled: true
  DocumentClassificationMonitorJob:
    every: '1m'
    queue: document_classification_monitor_job
    enabled: true
  OcrMonitorJob:
    every: '1m'
    queue: ocr_monitor_job
    enabled: true