:concurrency: 1
:queues:
  - ['default', 1]
  - ['ocr', 1]
  - ['document_classification', 1]
  - ['form_deep_understanding', 1]
:timeout: 7200

:schedule:
  OcrJob:
    every: '10s'
    queue: ocr
    enabled: true
  DocumentClassificationJob:
    every: '10s'
    queue: document_classification
    enabled: true